### ISSUE TITLE
plugin not working with latest eduke?

### ISSUE THREAD

**Issue by zoulztealer** [NightFright2k19/duke3d_widefix#4]
just tried to run this with the latest build (eduke32_win64_20210713-9476-3191b5f41).

i put the zip file in the autoload folder, but nothing happens.

the menu fonts stay the same low res as before.

when i put hrp and the fix in at the same time, hrp wont work at all.

when i extracted the fix files in the autoload folder, the font changed, but it was still low res.

however i try to turn and fit this, this plugin doesnt work or doesnt do anything for me.

using duke3d grp and rts from steam version.

**Comment by NightFright2k19** [comment]
I am using r9476 and have no problems. Must be an issue on your end. Please note that only one file can be active at a time and as soon as you place more than one mod with duke3d.def and/or eduke.con in autoload, only the last one in the list (sorted alphabetically by name) will be loaded.
