### ISSUE TITLE
[Suggestion] Revise stretched graphics

### ISSUE THREAD

**Issue by OpenRift412** [NightFright2k19/duke3d_widefix#5]
Just thought I'd drop some feedback here. I think the 3D Realms logo among other certain graphics in this pack looks kind of... off, since it's stretched to widescreen instead of having a supplementary texture filling in the negative space. It just feels a bit out of place compared to the quality of every other graphic in the pack.

Same with the "Play On TEN" and Duke Caribbean stats screen. 

I'd say scrap the wide 3DR logo all together since the original doesn't really go to the edges of the screen to begin with.

Here's some fixed versions of the "Play on TEN" screens for starters.

![2500](https://user-images.githubusercontent.com/29780788/147610486-1272cc58-96e3-41dc-a8aa-8b7ce67d0328.png)
![2500_wt](https://user-images.githubusercontent.com/29780788/147610488-a0311d57-9082-4ff6-9793-1f58b2a55cf8.png)

**Comment by NightFright2k19** [comment]
This project is by no means final and stretched graphics were used as placeholders. Remove them at will by yourself if you don't like them, but I won't do that here until proper ones are available. 
Note that I am not a pixel artist like Nash from the Doom community and did my best to provide as many widescreen assets as possible, by any means necessary.
