### ISSUE TITLE
[Question] How to use the old font with this mod?

### ISSUE THREAD

**Issue by valter12437** [NightFright2k19/duke3d_widefix#8]
Could someone please explain how to use the old font with this patch? Which files do I need to change to achieve that?

**Comment by NightFright2k19** [comment]
Define "old font". The one from Duke3D v1.3D? That one is included with this project. If you don't want it and prefer the Atomic (v1.5) font, just delete the three art files (tiles097-099.art) from the widefix zipfile.

**Comment by valter12437** [comment]
Yes, that's what I meant! Thank you! Sorry if I was unclear with my wording.
