### ISSUE TITLE
[Feature Request] support for JFDuke3D

### ISSUE THREAD

**Issue by vanfanel** [NightFright2k19/duke3d_widefix#9]
Hi there,

I am trying to make this mod work on JFDuke3D, since it supports widescreen video modes and it's a fantastic light sourceport that works on low performance hardware like Raspberry Pi, etc, even using GLES.

The only problem is, well, the weapons, tittle screen and Duke animations look incomplete in those widescreen modes, which this mod seems to address.

However, it doesn't seem to work with JFDuke.
I have begun investigation, and have requested some help from Jonathon Fowler here:
https://github.com/jonof/jfduke3d/issues/19
...but I suspect the mod format is tailored towards eduke32, etc.
JFDuke3D is still a thing, and as I said it's very useful: can you at least give me some pointers to adapt this so it works on JFDuke3D, please?

Thanks!

**Comment by NightFright2k19** [comment]
Sorry, but I have no experience with this port and its limited capabilites. Most of the def code used probably does not exist there and finding workarounds might be hard or even impossible. TBH I also don't see any point in diving into mysteries of a legacy port which is hardly used by anybody these days.

Update:
[I have forwarded your request to the Duke4.net forums](https://forums.duke4.net/topic/11659-release-widescreen-fixes-for-duke3d/page__st__90__gopid__381016#entry381016). Maybe someone over there is able to help. That's as much as I'm able (and willing) to do.

**Comment by vanfanel** [comment]
> Sorry, but I have no experience with this port and its limited capabilites. Most of the def code used probably does not exist there and finding workarounds might be hard or even impossible. TBH I also don't see any point in diving into mysteries of a legacy port which is hardly used by anybody these days.
> 
> Update: [I have forwarded your request to the Duke4.net forums](https://forums.duke4.net/topic/11659-release-widescreen-fixes-for-duke3d/page__st__90__gopid__381016#entry381016). Maybe someone over there is able to help. That's as much as I'm able (and willing) to do.

Thanks! That was very nice!

Let's hope somebody knows over there...
Oh, and JFDuke does support widescreen graphic modes, thats for sure.

**Comment by NightFright2k19** [comment]
[So even JonoF himself says it's a lost cause.](https://forums.duke4.net/topic/11659-release-widescreen-fixes-for-duke3d/page__view__findpost__p__381022)

I don't know what you really want with that old port. It may have a build from 2021, but it doesn't mean it's state-of-the-art. If you are looking for a vanilla-friendly port, check out Rednukem. Yes, it comes from EDuke32, but it's so close to vanilla you won't notice any difference. And, most importantly: This mod works with it.

As it stands now, JFDuke3D doesn't support pretty much _any_ function this mod requires and that won't change. It's not an actively developed port and won't receive any new features. On the other hand, I cannot make the mod work with it in any other way. Which translates into: Not possible.

**Comment by vanfanel** [comment]
Thanks for taking the time to look intro It, really.

As a final note, the main advantage or JFDuke IS that It works better on the Raspberry Pi, It seems to have way less overhead than Eduke32.
